import os

import psycopg
from dotenv import load_dotenv


load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")

if not DATABASE_URL:
    raise RuntimeError(
        "DATABASE_URL was not found. Check the .env file."
    )


POSTGRES_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS app_settings (
    setting_key TEXT PRIMARY KEY,
    setting_value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS recipes (
    recipe_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_name TEXT NOT NULL UNIQUE,
    meal_type TEXT NOT NULL CHECK (
        meal_type IN (
            'Breakfast',
            'Lunch',
            'Dinner',
            'Snack'
        )
    ),
    servings DOUBLE PRECISION NOT NULL CHECK (
        servings > 0
    ),
    calories_per_serving DOUBLE PRECISION NOT NULL DEFAULT 0,
    protein_per_serving DOUBLE PRECISION NOT NULL DEFAULT 0,
    carbs_per_serving DOUBLE PRECISION NOT NULL DEFAULT 0,
    fat_per_serving DOUBLE PRECISION NOT NULL DEFAULT 0,
    prep_minutes INTEGER NOT NULL DEFAULT 0,
    estimated_cost_per_serving DOUBLE PRECISION
        NOT NULL DEFAULT 0,
    instructions TEXT,
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ingredients (
    ingredient_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_name TEXT NOT NULL UNIQUE,
    category TEXT NOT NULL,
    preferred_store TEXT NOT NULL CHECK (
        preferred_store IN (
            'Aldi',
            'Costco',
            'Other'
        )
    ),
    default_unit TEXT NOT NULL,
    estimated_unit_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    package_quantity DOUBLE PRECISION,
    package_unit TEXT,
    package_price DOUBLE PRECISION,
    package_description TEXT,
    is_active INTEGER NOT NULL DEFAULT 1 CHECK (
        is_active IN (0, 1)
    )
);

CREATE TABLE IF NOT EXISTS recipe_ingredients (
    recipe_ingredient_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL,
    ingredient_id BIGINT NOT NULL,
    quantity DOUBLE PRECISION NOT NULL CHECK (
        quantity > 0
    ),
    unit TEXT NOT NULL,
    estimated_cost DOUBLE PRECISION NOT NULL DEFAULT 0,

    CONSTRAINT fk_recipe_ingredients_recipe
        FOREIGN KEY (recipe_id)
        REFERENCES recipes(recipe_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_recipe_ingredients_ingredient
        FOREIGN KEY (ingredient_id)
        REFERENCES ingredients(ingredient_id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_recipe_ingredient
        UNIQUE (recipe_id, ingredient_id)
);

CREATE TABLE IF NOT EXISTS meal_log (
    meal_log_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_date DATE NOT NULL,
    meal_type TEXT NOT NULL CHECK (
        meal_type IN (
            'Breakfast',
            'Lunch',
            'Dinner',
            'Snack'
        )
    ),
    recipe_id BIGINT NOT NULL,
    servings DOUBLE PRECISION NOT NULL DEFAULT 1 CHECK (
        servings > 0
    ),
    notes TEXT,
    calories_snapshot DOUBLE PRECISION,
    protein_snapshot DOUBLE PRECISION,
    carbs_snapshot DOUBLE PRECISION,
    fat_snapshot DOUBLE PRECISION,
    cost_snapshot DOUBLE PRECISION,
    pantry_deducted INTEGER NOT NULL DEFAULT 0 CHECK (
        pantry_deducted IN (0, 1)
    ),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_meal_log_recipe
        FOREIGN KEY (recipe_id)
        REFERENCES recipes(recipe_id)
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS meal_plan (
    meal_plan_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_date DATE NOT NULL,
    meal_type TEXT NOT NULL CHECK (
        meal_type IN (
            'Breakfast',
            'Lunch',
            'Dinner',
            'Snack'
        )
    ),
    recipe_id BIGINT NOT NULL,
    servings DOUBLE PRECISION NOT NULL DEFAULT 1 CHECK (
        servings > 0
    ),
    notes TEXT,
    is_logged INTEGER NOT NULL DEFAULT 0 CHECK (
        is_logged IN (0, 1)
    ),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_meal_plan_recipe
        FOREIGN KEY (recipe_id)
        REFERENCES recipes(recipe_id)
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS pantry_inventory (
    pantry_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id BIGINT NOT NULL UNIQUE,
    quantity_on_hand DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (
        quantity_on_hand >= 0
    ),
    unit TEXT NOT NULL,
    minimum_quantity DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (
        minimum_quantity >= 0
    ),
    expiration_date DATE,
    notes TEXT,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_pantry_ingredient
        FOREIGN KEY (ingredient_id)
        REFERENCES ingredients(ingredient_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS pantry_transactions (
    pantry_transaction_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pantry_id BIGINT NOT NULL,
    ingredient_id BIGINT NOT NULL,
    meal_log_id BIGINT,
    transaction_type TEXT NOT NULL CHECK (
        transaction_type IN (
            'Meal deduction',
            'Meal restoration',
            'Manual adjustment',
            'Purchase'
        )
    ),
    quantity_change DOUBLE PRECISION NOT NULL,
    unit TEXT NOT NULL,
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_pantry_transactions_pantry
        FOREIGN KEY (pantry_id)
        REFERENCES pantry_inventory(pantry_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_pantry_transactions_ingredient
        FOREIGN KEY (ingredient_id)
        REFERENCES ingredients(ingredient_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_pantry_transactions_meal_log
        FOREIGN KEY (meal_log_id)
        REFERENCES meal_log(meal_log_id)
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS shopping_trips (
    shopping_trip_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_name TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status TEXT NOT NULL DEFAULT 'Open' CHECK (
        status IN (
            'Open',
            'Completed'
        )
    ),
    estimated_checkout_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    actual_total_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shopping_trip_items (
    shopping_trip_item_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shopping_trip_id BIGINT NOT NULL,
    ingredient_id BIGINT NOT NULL,

    required_quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
    need_to_buy_quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
    need_unit TEXT NOT NULL,

    package_quantity DOUBLE PRECISION,
    package_unit TEXT,
    packages_planned INTEGER NOT NULL DEFAULT 0,
    planned_purchase_quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
    estimated_checkout_cost DOUBLE PRECISION NOT NULL DEFAULT 0,

    preferred_store TEXT,

    purchased INTEGER NOT NULL DEFAULT 0 CHECK (
        purchased IN (0, 1)
    ),
    actual_quantity DOUBLE PRECISION,
    actual_unit TEXT,
    actual_price DOUBLE PRECISION,
    actual_store TEXT,

    pantry_added INTEGER NOT NULL DEFAULT 0 CHECK (
        pantry_added IN (0, 1)
    ),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_shopping_trip_items_trip
        FOREIGN KEY (shopping_trip_id)
        REFERENCES shopping_trips(shopping_trip_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_shopping_trip_items_ingredient
        FOREIGN KEY (ingredient_id)
        REFERENCES ingredients(ingredient_id)
        ON DELETE RESTRICT
);

CREATE OR REPLACE VIEW recipe_cost_summary AS
SELECT
    r.recipe_id,
    COUNT(ri.recipe_ingredient_id) AS ingredient_count,
    COALESCE(
        SUM(ri.estimated_cost),
        0
    ) AS total_ingredient_cost,

    CASE
        WHEN COUNT(ri.recipe_ingredient_id) > 0
            THEN (
                COALESCE(
                    SUM(ri.estimated_cost),
                    0
                )
                / r.servings
            )
        ELSE COALESCE(
            r.estimated_cost_per_serving,
            0
        )
    END AS effective_cost_per_serving

FROM recipes AS r

LEFT JOIN recipe_ingredients AS ri
    ON r.recipe_id = ri.recipe_id

GROUP BY
    r.recipe_id,
    r.servings,
    r.estimated_cost_per_serving;
"""


DEFAULT_SETTINGS = {
    "daily_protein_goal": "180",
    "daily_calorie_goal": "2200",
    "weekly_grocery_budget": "100",
}


def initialize_postgres() -> None:
    with psycopg.connect(
        DATABASE_URL,
        autocommit=False,
    ) as connection:
        try:
            connection.execute(
                POSTGRES_SCHEMA_SQL
            )

            for setting_key, setting_value in (
                DEFAULT_SETTINGS.items()
            ):
                connection.execute(
                    """
                    INSERT INTO app_settings (
                        setting_key,
                        setting_value
                    )
                    VALUES (%s, %s)
                    ON CONFLICT (setting_key)
                    DO NOTHING
                    """,
                    (
                        setting_key,
                        setting_value,
                    ),
                )

            connection.commit()

        except Exception:
            connection.rollback()
            raise


if __name__ == "__main__":
    initialize_postgres()
    print(
        "PostgreSQL schema initialized successfully."
    )